# Generated by Django 2.0.2 on 2018-03-30 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beeflow', '0005_flowrecord_flow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='_FlowBecome_Full_Staff',
            new_name='FlowBecome_Full_Staff',
        ),
        migrations.RenameModel(
            old_name='_FlowLoan',
            new_name='FlowLoan',
        ),
        migrations.RenameModel(
            old_name='_FlowTrip',
            new_name='FlowTrip',
        ),
        migrations.RenameModel(
            old_name='_FlowVaction',
            new_name='FlowVaction',
        ),
    ]
